---
- name: Download Homebrew Installer (brew.sh)
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
    dest: /tmp/install.sh

- name: Install Latest Homebrew (brew.sh)
  ansible.builtin.shell: /tmp/install/install.sh
  become: yes

- name: brew install cybr-cli
  ansible.builtin.shell: brew install infamousjoeg/tap/cybr-cli

- name: Login to cybr-cli for PAS
  ansible.builtin.shell: "cybr logon -u {{ cyberark.username }} -a {{ cyberark.auth_type }} -b {{ cyberark.pvwa_url }} -p {{ cyberark.password }} --non-interactive"

- name: List All Accounts in PAS
  ansible.builtin.shell: cybr accounts list
