---
- name: Download & Install Latest cybr-cli
  ansible.builtin.unarchive:
    src: https://github.com/infamousjoeg/cybr-cli/releases/latest/download/cybr-cli_linux_amd64.tar.gz
    dest: /usr/local/bin
    remote_src: yes
  become: yes

- debug:
    var: cyberark.username
- debug:
    var: cyberark.auth_type
- debug:
    var: cyberark.pvwa_url
- debug:
    var: cyberark.test

- name: Login to cybr-cli for PAS
  ansible.builtin.shell: "cybr logon -u {{ cyberark.username }} -a {{ cyberark.auth_type }} -b {{ cyberark.pvwa_url }} -p {{ cyberark.password }} --non-interactive"

- name: List All Accounts in PAS
  ansible.builtin.shell: cybr accounts list
