- hosts: localhost
  tasks:
    - ansible.builtin.shell: ansible-galaxy collection install cyberark.conjur --collections-path /home/runner/.ansible/collections

- hosts: all
  gather_facts: no
  
  #roles:
  #  - { role: "roles/os-patching" }
  tasks:
    - set_fact:
        ansible_ssh_pass: "{{ lookup('cyberark.conjur.conjur_variable', 'SyncVault/LOB_CD/D-Nix-Root/Operating System-UnixSSH-' + inventory_hostname + '-root/username ') }}"
      delegate_to: localhost

    - ansible.builtin.shell: ansible-galaxy collection list