---
- name: Gathering ipam auth token
  hosts: all
  uri:
    validate_certs: false
    url: "{{ ipam.token_request }}"
    method: POST
    user: "{{ ipam.api_user }}"
    password: "{{ ipam.api_pass | trim }}"
    force_basic_auth: yes
  register: output

- name: checking subnet for next available ip address
  uri:
    validate_certs: false
    url: "{{ ipam.available_ip }}{{ ipam.subnet_id | int }}"
    headers: token="{{ output.json.data.token }}"
  register: ip_address

- name: reserve ip address
  uri:
    validate_certs: false
    url: "{{ ipam.available_ip }}{{ ipam.subnet_id | int }}"
