---
- name: uri module demo
  hosts: all
  become: false
  vars:
    server: "https://ipam.telecom.tcnz.net"
    endpoint: "/api/login"
  tasks:
    - name: login
      ansible.builtin.uri:
        url: "{{ server }}{{ endpoint }}"
        method: POST
        body_format: json
        body: '{
          "email": "mcm-svc",
          "password": "Bhadru01"
        }'
        status_code: 200
        timeout: 30
      register: result
    - name: token
      ansible.builtin.debug:
