---
- name: Check if RHEL
  set_fact:
    tag_role: 'client_rhel'
  when: os_platform == 'rhel'

- name: Check if Ubuntu
  set_fact:
    tag_role: 'client_ubuntu'
  when: os_platform == 'ubuntu'

- name: Check if Amazon Linux
  set_fact:
    tag_role: 'client_amazonlinux'
  when: os_platform == 'amazonlinux'

- name: Get AWS EC2 Instance IDs
  amazon.aws.ec2_instance_info:
    region: "{{ region }}"
    filters:
      "tag:role": "{{ tag_role }}"
      instance-state-name: [ "running" ]
  when: os_platform != 'all'
  register: ec2_instances

- name: "Terminate All {{ os_platform }} AWS EC2 Instances"
  ec2:
    region: "{{ region }}"
    instance_ids: "{{ item.instance_id }}"
    state: absent
  with_items: "{{ ec2_instances.instances }}"
  when: os_platform != 'all'

- name: Terminate All AWS EC2 Instances
  amazon.aws.ec2_instance:
    filters:
      instance-state-name: running
    state: absent
  when: os_platform == 'all'
