name: Ansible Lint

on: push

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Lint AWS EC2 Deprovision Playbooks
      uses: ansible/ansible-lint-action@master
      with:
        targets: "awsec2-deprovision/"
        args: ""
    - name: Lint AWS EC2 Provision Playbooks
      uses: ansible/ansible-lint-action@master
      with:
        targets: "awsec2-provision/"
        args: ""
    - name: Lint Root Repository Playbooks
      uses: ansible/ansible-lint-action@master
      with:
        targets: "/"
        args: "-x 301"
